### ISSUE TITLE
where is the "corenlp.sh"?

### ISSUE THREAD

**Issue by HiXiaochen** [ShuyangCao/open-ended_question_ontology#1]
I want to follow the README guidelines for data processing, but i can't find the file "corenlp.sh".

**Comment by FengKaiqi** [comment]
> I want to follow the README guidelines for data processing, but i can't find the file "corenlp.sh".
Hello, Have you ever solved this problem? I cannot find a suitable version of CoreNLP that can be used in Visual Code.
I am looking forward to your reply.
