### ISSUE TITLE
Possible bug for convert_to_single_files.py?

### ISSUE THREAD

**Issue by dxlong2000** [ShuyangCao/open-ended_question_ontology#5]
Hi Shuyang Cao,

Thanks for your great work. I have a question. In the convert_to_single_files.py:

```
out_path = os.path.join(args.out_dir, f'{id}.question')
        with open(out_path, 'w') as f:
            f.write(answer)
        out_paths.append(out_path)
```
Is ```answer``` here should be ```question```?
Thanks!

**Comment by ShuyangCao** [comment]
Thanks for pointing it out! The original code implementation actually has two files: `convert_to_single_files_answer.py` and `convert_to_single_files_question.py`. Forgot to change the variable name after combining them.
