### ISSUE TITLE
Training script for explgen

### ISSUE THREAD

**Issue by dxlong2000** [ShuyangCao/open-ended_question_ontology#6]
Hi @ShuyangCao ,

Thanks for your great work. I have one question regarding the training script of ```explgen.sh``` and ```tplgen_template_generation.sh``` . Are they supposed to exchange the content? Since inside the ```explgen.sh``` you specified the content from ```tplgen``` and inside ```tplgen_template_generation.sh``` you specified the content from ```explgen```?

**Comment by ShuyangCao** [comment]
Somehow I copy the content that should be in `tplgen_question_generation.sh` to `explgen.sh` (if you haven't pulled since last hour, you would find that `tplgen_question_generation.sh` is empty). Now it should be good.
